### ISSUE TITLE
[Bugs]About Deploy Cluster

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1021]
**Descriptions**:
Deploy cluster on docker, 3 containers used. 
Bug 1: When I killed a storage process, nebula will still send requests when reading the data.
Bug2: I have 3 replicas when one is killed and new leader is not elected yet, nebula will keep reading data, I think the supposed behavior is returning nothing and throw an error.
Bug 3: Parameter display, when I change the `expired_threshold_sec`, nebula still shows the default value.
**Environment**:
Docker nightly
**How To Reproduce**
Deploy cluster on docker and test deployment will show the above bugs.
**Additional context**
I think inconsistent data is returned due to Bug 1 and Bug 2, when one of the three storage processes is dead, the returned data is as follow:
![image](https://user-images.githubusercontent.com/42762957/66452515-59d90e00-ea93-11e9-9ddb-3ab38255dbd6.png)
the supposed data is 
![image](https://user-images.githubusercontent.com/42762957/66452531-6b221a80-ea93-11e9-8922-b79650a9f2d7.png)

What's more, I changed the file nebula-metad.conf
![image](https://user-images.githubusercontent.com/42762957/66452557-8856e900-ea93-11e9-9066-5975d7eaf09b.png)
but the displayed parameter is still the default value
![image](https://user-images.githubusercontent.com/42762957/66452622-cd7b1b00-ea93-11e9-8a70-51f6e1a80db2.png)
Besides, I can't change the parameter with the command taught in file https://github.com/vesoft-inc/nebula/blob/153545e1937ae1f0b426cf04d26a5f356a63043c/docs/manual-EN/statement-syntax/data-administration-statements/configuration-statements/variables-syntax.md#update-variables
![image](https://user-images.githubusercontent.com/42762957/66452689-09ae7b80-ea94-11e9-913d-a9867227b6f4.png)

**Comment by critical27** [comment]
1. This is because the communication between different dockers of storage is blocked, maybe need to expose the port between them. 

2. We can't change the parameter of meta, `expired_threshold_sec` in your issue. We can only set them in nebula-metad.conf. And all configs in meta will be immutable. So if you have start meta before, the `expired_threshold_sec` will always be the first value when meta start up. If you do want to update them, you need to clear data in meta, and set them in `nebula-metad.conf`.
