### ISSUE TITLE
Index creation succeed before rebuilding

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#2182]
I created an index after data insertion. When I `LOOKUP` data, nothing returned. I know this is because the index is not rebuilt so that it's not yet available. But when I run `SHOW TAG INDEX STATUS`, the `SUCCEEDED` status is returned. I'm expecting an empty returned result. Because the index is invalid. What's more, when I run the above statements for the first time,  an empty result is returned. 

I don't know why the returned result is different when I dropped the index and re-built the SAME INDEX for the second time.

Any ideas?

**Comment by bright-starry-sky** [comment]
The reason is rebuild status information disrupted. We need to delete the status information along with deleting the index.

For example :
1 . create index
2. show index status --> here empty result expected. works well at step.
3, rebuild index offline
4. show index status --> here return index status info expected. works well at step.
5, drop index 
6. show index status --> here empty result expected. but still returned index status row, because the status information from the last rebuild index is still there.

I will push a PR later, let delete the index status information with drop index together.

**Comment by bright-starry-sky** [comment]
PR #2183 fixed this issue.
