### ISSUE TITLE
0.0.0.0 configured, but server listens on both ipv4 and ipv6

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula#3936]
3.0 seems to changed the behavior of serving based on host ip(differentiated from 2.0).
It's reported it's listening not just all v4 hosts but also v6 hosts.

https://discuss.nebula-graph.com.cn/t/topic/7655?u=wey

**Comment by CPWstatic** [comment]
Sorry, the thrift server will try to bind ipv6 first since nebula 2.0. It is not configurable as far as i know. And if server listen on ipv6, it can still receive ipv4 client package, so i think it will not bother you much. If binding to ipv6 is unacceptable on you environment, i suggest that you could manually forbidden ipv6 on your environment.
