### ISSUE TITLE
Why following query reports the confused errors?

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#4140]
**General Question**

Branch: master

```
GO 2 STEPS FROM 'Tim Duncan' OVER like WHERE $$.player.age > 20 Yield $$.player.name
```

error log:

```
E20220412 16:25:21.904093 98909 Optimizer.cpp:48] Failed to postprocess plan: EdgeName `*'  is nonexistent
```

What's the meaning of `EdgeName *`? This error was reported in Optimizer:

```
  auto status2 = postprocess(const_cast<PlanNode *>(newRoot), qctx, spaceID);
  if (!status2.ok()) {
    LOG(ERROR) << "Failed to postprocess plan: " << status2;
  }

```

**Comment by jievince** [comment]
The error is reported when trying to get the edge type of the given edge name.
And the `EdgeName *` is a special symbol that is widely used in our implementation for ngql.
You can search `"*"` in our code:
![image](https://user-images.githubusercontent.com/38901892/162942659-0b6fff4b-82aa-4b9d-aee1-625dee3b59a6.png)
This error reported for ngql could be ignored because it's designed for the property pruner rule which will only affect `MATCH` statement.
