### ISSUE TITLE
Nebula console can't  recognize the backspace  key in windows' WSL environment 

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#434]
my environment is a bit complex:

run docker on windows, and run docker cli on wsl(windows subsystem linux.

I can start nebula services and nubula console successfully. And i can use shell commands in the docker. Also, the Backspace key works good in the shell.

BUT, there is a tiny problem in the nubula cosole (which is started by the command ./start-console.sh):

this console can't recognize the backspace key. it seems to re-interpret the backspace key as the right-arrow key. Besides, all the arrow keys do not work. 

It's a bit hard to type correct every time for me :-)

So far, all other keys worked well in nebula console. 

Do you guys have any idea?

**Comment by sherman-the-tank** [comment]
👍

**Comment by dutor** [comment]
@laura-ding encountered the same issue before.

After some investigations, I found it's due to the *ncurses* library. In the CentOS 7.x environments, we have been using a self-compiled, newer version than the system-wide one. This incurs some binary level imcompatibilities.

To address this problem, we just switch use *libreadline* and *libncurses* shipped with the system, and link against them in a dynamic way.

Besides, if we are going to remove these two libraries from the *engshare* repo, we need remove *lua* from it too, since *lua* depends on them(newer version). Further more, if we want to keep *lua*, we have to check if we could remove the dependencies.


@whitewum Thanks for pointing this out.

**Comment by dutor** [comment]
@darionyaphet @laura-ding We need to rebuild our Docker image, with two CMake macros removed, i.e. `-DNEBULA_READLINE_ROOT=/home/engshare/readline -DNEBULA_NCURSES_ROOT=/home/engshare/ncurses`

**Comment by dutor** [comment]
This issue has been already addressed in the new release of our docker image, without any source code changed.

**Comment by whitewum** [comment]
Now the console is ok in WSL. Thank you for your quick response.
