### ISSUE TITLE
stop rebuild tag index job, but it failed

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula#4485]
**Please check the FAQ documentation before raising an issue**

1.when i stop a "running rebuild tag index" job, firstly it stopped, then it failed; I found one storage node is failed, and the whole status was failed;
2.I rebuild a new tag  index job, the  former failed storage node always failed;
you can see the second picture；
![image](https://user-images.githubusercontent.com/106510322/182797198-414f76d4-fbad-4afd-b36a-aacc1ce67475.png)
![image](https://user-images.githubusercontent.com/106510322/182797766-7e4a0c9e-d668-4bbe-a48b-ad9ff0274c3d.png)

**Your Environments (__required__)**
with mater brunch，Git: 21ee515 
![image](https://user-images.githubusercontent.com/106510322/182798410-6733a9b1-c5aa-4941-95bb-7bedd9eebedd.png)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by critical27** [comment]
I guess 1512 work as expected?
1.  `stop job 1512; show job 1512`, the job will be marked as stopped in meta.
2. meta tell storage
3. storage report USER_CANCEL in async to meta
4. because it is not a ok, so it will modify the job status to failed.

1513 is probably another reason, nit quite same problem

**Comment by Sophie-Xie** [comment]
Discuss offline: state machine of job manager needs to be redesigned in 5.x.
