### ISSUE TITLE
Do we officially support to use clang to compile nebula? If we do, on which version ? Thanks

### ISSUE THREAD

**Issue by mo-avatar** [vesoft-inc/nebula#5519]
Do we officially support to use clang to compile nebula? If we do, on which version ? Thanks

**Comment by wey-gu** [comment]
Yes, if you look into the CI in each PR, you will notice it's complied with both gcc and clang, I don't recall since when it's supported, I would say it's supported for long time already.

- https://github.com/vesoft-inc/nebula/blob/ac79d85832147106b3cf1b48ff7dd0fdc76cad11/.github/workflows/pull_request.yml#L63
- https://github.com/vesoft-inc/nebula-third-party/

**Comment by mo-avatar** [comment]
> Yes, if you look into the CI in each PR, you will notice it's complied with both gcc and clang, I don't recall since when it's supported, I would say it's supported for long time already.
> 
> * https://github.com/vesoft-inc/nebula/blob/ac79d85832147106b3cf1b48ff7dd0fdc76cad11/.github/workflows/pull_request.yml#L63
> * https://github.com/vesoft-inc/nebula-third-party/

Thanks for your answer, It's my fault not to make the problem clear , what I want to ask is the clang version we have tested to make nebula to work in production. but you have answered that too -- clang-10 I think.

**Comment by wey-gu** [comment]
Welcome @mo-avatar !

Could you please help confirm the most production-verified binary packages are gcc or clang based? @Shinji-IkariG  Thanks!

**Comment by Shinji-IkariG** [comment]
Our release packages are usually based on gcc, but clang10 has started to support it 2 years ago

**Comment by mo-avatar** [comment]
> Our release packages are usually based on gcc, but clang10 has started to support it 2 years ago

I see,  we may keep to use gcc in production, thanks for your answer
