### ISSUE TITLE
Fix compile warnings in hbase.thrift.

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#558]
hbase.thrift:314] required keyword is ignored in argument lists.

@zhangguoqing Could you take a look? Thanks.

**Comment by dutor** [comment]
FYI.

I just had a skim on the grammer specs of **fb**thrift. I found that `optional` AND `required` are not supposed to appear in a argument list of a function/method. But `required` itself seems to be supported in Apache Thrift in such case.

I have tried to remove these `required`s. It turns out OK for **building**.
